route:
  receiver: 'discord_webhook'
  repeat_interval: 4h
  group_by: [ altername ]
  group_wait: 1s
  group_interval: 1s

receivers:
  - name: 'discord_webhook'
    webhook_configs:
      - url: 'http://discord_alerts:9094'