version: '3.9'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  monitoring:
    driver: bridge

services:
  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring

  grafana:
    build: ./grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring

  blackbox_exporter:
    build: ./blackbox_exporter
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    command: 
      - "--config.file=/etc/blackbox_exporter/blackbox.yml"
    restart: unless-stopped
    networks:
      - monitoring

  test_application:
    build: ./test_application
    container_name: test_application_container
    ports:
      - "8000:5000"
    networks:
      - monitoring
  redis:
    image: "redis:alpine"
    container_name: redis-test_application
    networks:
      - monitoring